name: ENV Variables
on: push
env:
  WF_ENV: Available to all jobs
  

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        env:
          STEP_ENV: Available to  only this step
        run: |
          echo "WF_ENV:${WF_ENV}"
          echo "JOB_ENV:${JOB_ENV}"
          echo "STEP_ENV:${STEP_ENV}"
      - name: Log ENV 2
        run: |
          echo "WF_ENV:${WF_ENV}"
          echo "JOB_ENV:${JOB_ENV}"
          echo "STEP_ENV:${STEP_ENV}"
        
          