name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "hello world!"
      - name: multiline script
        run: |
          node -v
          npm -v
          